#!/usr/bin/env node
import { spawn, spawnSync } from 'node:child_process';
import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const [mode = 'provider', ...args] = process.argv.slice(2);

if (mode === '--version') {
  process.stdout.write('roundtable-fixture 1.2.3\n');
} else if (mode === '--help' || args.includes('--help')) {
  process.stdout.write([
    '--ignore-user-config',
    '--ignore-rules',
    '--strict-config',
    '--sandbox',
    '--ephemeral',
    '--json',
    '--safe-mode',
    '--permission-mode',
    '--settings',
    '--setting-sources',
    '--strict-mcp-config',
    '--mcp-config',
    '--input-format',
    '--output-format',
    '--pure',
    '--auto',
    '--format',
    '--dir',
    '--agent',
  ].join('\n'));
} else if (mode === 'grandchild') {
  process.on('SIGTERM', () => undefined);
  setInterval(() => undefined, 1_000);
} else if (mode === 'tree') {
  const [pidFile] = args;
  if (!pidFile) process.exit(2);
  const child = spawn(process.execPath, [fileURLToPath(import.meta.url), 'grandchild'], {
    detached: false,
    stdio: 'ignore',
  });
  await writeFile(pidFile, JSON.stringify({ parent: process.pid, grandchild: child.pid }), 'utf8');
  process.on('SIGTERM', () => undefined);
  process.stdout.write('tree-ready\n');
  setInterval(() => undefined, 1_000);
} else if (mode === 'detached-tree') {
  const [pidFile] = args;
  if (!pidFile) process.exit(2);
  const child = spawn(process.execPath, [fileURLToPath(import.meta.url), 'grandchild'], {
    detached: true,
    stdio: ['ignore', 'inherit', 'inherit'],
  });
  await writeFile(pidFile, JSON.stringify({ parent: process.pid, grandchild: child.pid }), 'utf8');
  process.on('SIGTERM', () => undefined);
  process.stdout.write('detached-tree-ready\n');
  setInterval(() => undefined, 1_000);
} else if (mode === 'flood') {
  process.stdout.write('o'.repeat(2 * 1024 * 1024));
  process.stderr.write('e'.repeat(1024 * 1024));
} else if (mode === 'env') {
  process.stdout.write(JSON.stringify(process.env));
} else if (mode === 'artifact') {
  await writeFile(join(process.cwd(), 'generated.txt'), 'generated by fixture\n', 'utf8');
  process.stdout.write('artifact-created\n');
  process.stderr.write('fixture-diagnostic\n');
} else if (mode === 'idle') {
  setInterval(() => undefined, 1_000);
} else if (mode === 'busy') {
  setInterval(() => process.stdout.write('.'), 20);
} else if (mode === 'exec') {
  let prompt = '';
  for await (const chunk of process.stdin) prompt += chunk;
  if (prompt.includes('fixture:tree')) {
    const child = spawn(process.execPath, [fileURLToPath(import.meta.url), 'grandchild'], {
      detached: false,
      stdio: 'ignore',
    });
    await writeFile(
      join(process.cwd(), '.fixture-pids.json'),
      JSON.stringify({ parent: process.pid, grandchild: child.pid }),
      'utf8',
    );
    process.on('SIGTERM', () => undefined);
    process.stdout.write('tree-ready\n');
    setInterval(() => undefined, 1_000);
  } else if (prompt.includes('fixture:rapid-native-tree:')) {
    const launcher = prompt.split('fixture:rapid-native-tree:')[1]?.trim() ?? '';
    const pidFile = join(process.cwd(), '.fixture-rapid-pids.json');
    const launched = spawnSync(launcher, [pidFile], {
      cwd: process.cwd(),
      env: { PATH: '/usr/bin:/bin' },
      stdio: 'ignore',
      shell: false,
      timeout: 2_000,
    });
    if (launched.error || launched.status !== 0 || launched.signal !== null) {
      process.stderr.write('rapid-native-tree-failed\n');
      process.exitCode = 3;
    } else {
      process.stdout.write('rapid-native-tree-launched\n');
    }
  } else if (prompt.includes('fixture:split-redaction:')) {
    const secret = prompt.split('fixture:split-redaction:')[1]?.trim() ?? '';
    process.stdout.write(`prefix ${secret.slice(0, 7)}`);
    await new Promise((resolve) => setTimeout(resolve, 20));
    process.stdout.write(`${secret.slice(7)} suffix`);
  } else if (prompt.includes('fixture:create-artifact')) {
    await writeFile(join(process.cwd(), 'provider-generated.txt'), `${prompt.trim()}\n`, 'utf8');
    process.stdout.write(JSON.stringify({ type: 'fixture.result', promptBytes: Buffer.byteLength(prompt) }));
  } else if (prompt.includes('fixture:print-env')) {
    process.stdout.write(JSON.stringify(process.env));
  } else {
    process.stdout.write(JSON.stringify({ type: 'fixture.result', promptBytes: Buffer.byteLength(prompt) }));
  }
} else {
  process.stderr.write('unsupported-fixture-mode\n');
  process.exitCode = 2;
}
