// Generated by scripts/build-native-helper.mjs. Do not edit by hand.
export type NativeHelperManifestEntry = Readonly<{
  size: number;
  sha256: string;
}>;

export const NATIVE_HELPER_MANIFEST: Readonly<Record<string, NativeHelperManifestEntry>> = Object.freeze({
  arm64: Object.freeze({
    size: 54824,
    sha256: '35964fb5ffe8370de82ae75c6bc0d38d6e6e84353a3c5a3d3fee406e8ed891d5',
  }),
  x64: Object.freeze({
    size: 33720,
    sha256: 'd2cea188bf6a2f1592feaa3c07686b5b189ba2e475381ce05e299a457a6475a3',
  }),
});

export const NATIVE_BOUNDARY_PROBE_MANIFEST: Readonly<Record<string, NativeHelperManifestEntry>> = Object.freeze({
  arm64: Object.freeze({
    size: 33992,
    sha256: '49b135deb4e8fd340cdf4b027b7930d7b204c7e0a25d1320cd68129b90b63fbc',
  }),
  x64: Object.freeze({
    size: 8960,
    sha256: '1b0cacef443efa8dbcce911b66921627cc6d39e65428a518b7adf34d256db520',
  }),
});

export const NATIVE_ADMINISTRATOR_HELPER_MANIFEST: Readonly<Record<string, NativeHelperManifestEntry>> = Object.freeze({
  arm64: Object.freeze({
    size: 52104,
    sha256: '861843cb13cfb6e4bc2d93b3997b81571ad31dfc8f28367fab99f2effa0510e7',
  }),
  x64: Object.freeze({
    size: 18760,
    sha256: '3b8a3c4c257c58a177fdf494fbbc5845ddc5749a224359f4c0c3d0b202fc6665',
  }),
});

export const NATIVE_AUTHORIZATION_LAUNCHER_MANIFEST: Readonly<Record<string, NativeHelperManifestEntry>> = Object.freeze({
  arm64: Object.freeze({
    size: 35400,
    sha256: '019bc2be10fec1979c9dc49d9d2407b8ad0ef29b80932631990ddbec26c6ab85',
  }),
  x64: Object.freeze({
    size: 14496,
    sha256: '6f008b111d68b037e4fceb1bda070880b7d4f87cab6deedb62fcf906ad97f7d5',
  }),
});
